### ISSUE TITLE
How do I generate the data? thanks a lot

### ISSUE THREAD

**Issue by kaicchenintel** [artificertxj1/HumanShapeNetworks#4]
How do I generate the data? thanks a lot

**Comment by artificertxj1** [comment]
Okay, here is a guide to generate the data.
You can use CAESAR. It's a commercial dataset. There is a parsed public dataset based on that from Max-Plank group at 
http://humanshape.mpi-inf.mpg.de/ 
After you have the LIDAR point cloud. The number of points in each data sample is same. Then, you can apply PCA to generate eigen-vectors. By my tests, first twenty eigen-vectors can cover up to 95% of human shape variance. So, from here, with 20 eigen vectors, you can change the weight of each vector and generate arbitrary human shape and project them to 2D images. 
About the human point cloud vector, for example, if you have 10000 points, then you can have a 1 by 30000 vector for each data sample composed by [x, y, z] coordinates of points. 
You can run Matlab codes to do PCA. 
Sorry for the late reply, I don't pay attention to this github account in the past few months.
If you have questions, please send me an email at justintian2017@outlook.com
Regards,
                                                 Justin Tian
