### ISSUE TITLE
Reproduce your results.

### ISSUE THREAD

**Issue by SergeyMalashenko** [artificertxj1/HumanShapeNetworks#6]
Good day! I want to reproduce your results, so as you mentioned in your README I should contact with you, but I didn't see your e-mail

**Comment by sklipnoty** [comment]
Yeah same problem. Where do we contact you?

**Comment by SergeyMalashenko** [comment]
You are not attentive and I am also :) Please check closed issues and you will find the answer

**Comment by artificertxj1** [comment]
Oh well, glad we have a small helpful discussion group here. I will close the issue
